=== nvolodymyr/Diamond_Fond/src/main/resources/Schema.xsd
<?xml version="1.0" ?>
<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema"
            targetNamespace="http://www.example.com/mns"
            xmlns:mns="http://www.example.com/mns">

    <xsd:element name="diamond">
        <xsd:complexType>
            <xsd:sequence>
                <xsd:element name="gems">
                    <xsd:complexType>
                        <xsd:sequence>
                            <xsd:element name="gem" type="mns:Gem" maxOccurs="unbounded"/>
                        </xsd:sequence>
                    </xsd:complexType>
                </xsd:element>
            </xsd:sequence>
        </xsd:complexType>
    </xsd:element>

    <xsd:complexType name="Gem">
        <xsd:sequence>
            <xsd:element name="name" type="xsd:string"/>
            <xsd:element name="preciousness" type="mns:Preciousness"/>
            <xsd:element name="origin" type="xsd:string"/>
            <xsd:element name="visualParameters" type="mns:VisualParameters"/>
            <xsd:element name="value" type="mns:Value"/>
        </xsd:sequence>
        <xsd:attribute name="id" type="mns:Id" use="required"/>
    </xsd:complexType>

    <xsd:complexType name="VisualParameters">
        <xsd:sequence>
            <xsd:element name="visualId" type="mns:VisualId"/>
            <xsd:element name="color" type="mns:Color" minOccurs="1" maxOccurs="1"/>
            <xsd:element name="transparency" type="mns:Transparency"/>
            <xsd:element name="gemCutting" type="mns:GemCutting"/>
        </xsd:sequence>
    </xsd:complexType>
    <xsd:simpleType name="VisualId">
        <xsd:restriction base="xsd:string">
            <xsd:pattern value="[A-Za-z0-9-]+"/>
        </xsd:restriction>
    </xsd:simpleType>

    <xsd:simpleType name="Id">
        <xsd:restriction base="xsd:string">
            <xsd:pattern value="[A-Za-z0-9-]+"/>
        </xsd:restriction>
    </xsd:simpleType>

    <xsd:simpleType name="Preciousness">
        <xsd:restriction base="xsd:string">
            <xsd:enumeration value="PRECIOUS"/>
            <xsd:enumeration value="SEMIPRECIOUS"/>
        </xsd:restriction>
    </xsd:simpleType>

    <xsd:simpleType name="Color">
        <xsd:restriction base="xsd:string">
            <xsd:enumeration value="RED"/>
            <xsd:enumeration value="ORANGE"/>
            <xsd:enumeration value="YELLOW"/>
            <xsd:enumeration value="GREEN"/>
            <xsd:enumeration value="BLUE"/>
            <xsd:enumeration value="VIOLET"/>
            <xsd:enumeration value="colorless"/>
        </xsd:restriction>
    </xsd:simpleType>

    <xsd:simpleType name="Transparency">
        <xsd:restriction base="xsd:int">
            <xsd:minInclusive value="0"/>
            <xsd:maxInclusive value="100"/>
        </xsd:restriction>
    </xsd:simpleType>

    <xsd:simpleType name="GemCutting">
        <xsd:restriction base="xsd:integer">
            <xsd:minInclusive value="4"/>
            <xsd:maxInclusive value="15"/>
        </xsd:restriction>
    </xsd:simpleType>

    <xsd:simpleType name="Value">
        <xsd:restriction base="xsd:float">
            <xsd:minInclusive value="0.01"/>
        </xsd:restriction>
    </xsd:simpleType>

</xsd:schema>

=== nvolodymyr/Diamond_Fond/src/main/resources/Diamonds.xml
<?xml version="1.0" ?>
<?xml-stylesheet href="Diamonds.xsl" type="text/xsl" ?>
<mns:diamond xmlns:mns="http://www.example.com/mns"
             xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
             xsi:schemaLocation="http://www.example.com/mns Schema.xsd">
    <gems>
        <gem id="1">
            <name>bla</name>
            <preciousness>PRECIOUS</preciousness>
            <origin>Vynnyky</origin>
            <visualParameters>
                <visualId>1</visualId>
                <color>GREEN</color>
                <transparency>100</transparency>
                <gemCutting>6</gemCutting>
            </visualParameters>
            <value>3.0</value>
        </gem>
        <gem id="2">
            <name>bla</name>
            <preciousness>SEMIPRECIOUS</preciousness>
            <origin>Vynnyky</origin>
            <visualParameters>
                <visualId>2</visualId>
                <color>RED</color>
                <transparency>80</transparency>
                <gemCutting>7</gemCutting>
            </visualParameters>
            <value>3.0</value>
        </gem>
    </gems>
</mns:diamond>
